### ISSUE TITLE
Fix displayed time in attendance table

### ISSUE THREAD

**Issue by codewhizz** [codeglitchz/attendance-system#15]
The time displayed in attendance table is when the attendance row is created.
Make that time dynamic and unique for each student entries for attendance

**Comment by JayRebuilds** [comment]
attendance-system) C:\python apps\attendance-system-master\backend>python run.py     
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from src.app import app
  File "C:\python apps\attendance-system-master\backend\src\app.py", line 9, in <module>
    from src.resources.dashboard import Dashboard
  File "C:\python apps\attendance-system-master\backend\src\resources\dashboard.py", line 2, in <module>
    from flask_jwt_extended import jwt_optional, get_jwt_identity
ImportError: cannot import name 'jwt_optional' from 'flask_jwt_extended' (C:\Users\Hp\.conda\envs\attendance-system\lib\site-packages\flask_jwt_extended\__init__.py)
