### ISSUE TITLE
think i miss some install instructions

### ISSUE THREAD

**Issue by zaanen** [codeglitchz/attendance-system#16]
when i try python or python3 run.py in de conda envirment i get the following errors.

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from src.app import app
  File "/home/pi/attendance-system/backend/src/app.py", line 11, in <module>
    from src.resources.student import StudentList, StudentAdd, StudentCapture, StudentDelete
  File "/home/pi/attendance-system/backend/src/resources/student.py", line 12, in <module>
    from src.libs.train_classifier import TrainClassifier
  File "/home/pi/attendance-system/backend/src/libs/train_classifier.py", line 7, in <module>
    from src.settings import DATASET_PATH, ENCODINGS_FILE, DLIB_MODEL
  File "/home/pi/attendance-system/backend/src/settings.py", line 5, in <module>
    class FlaskAppConfiguration:
  File "/home/pi/attendance-system/backend/src/settings.py", line 8, in FlaskAppConfiguration
    SECRET_KEY = config('SECRET_KEY')
  File "/home/pi/c4aarch64_installer/envs/attendance-system/lib/python3.7/site-packages/decouple.py", line 199, in __call__
    return self.config(*args, **kwargs)
  File "/home/pi/c4aarch64_installer/envs/attendance-system/lib/python3.7/site-packages/decouple.py", line 83, in __call__
    return self.get(*args, **kwargs)
  File "/home/pi/c4aarch64_installer/envs/attendance-system/lib/python3.7/site-packages/decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

**Comment by mdmujtabaraza** [comment]
Just rename `.env.example` file to `.env` in backend directory.

**Comment by zaanen** [comment]
thanks i tried that but i think i made a typo so it did not work. Now it works. 

For future development i think it would be nice to log on what attendance (classroom id the student was recorded in on check attendance. 
Then you could make indeed multiple classroom feeds and switch activation between them to register on witch they attended. 
Also adding extra pictures to a student would be nice i think.
