### ISSUE TITLE
Problem in the backend with JSON

### ISSUE THREAD

**Issue by AchrafELKADIRI99** [codeglitchz/attendance-system#20]
Error message : 
Traceback (most recent call last):
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask_restful\__init__.py", line 471, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask_restful\__init__.py", line 500, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\Users\achra\.conda\envs\attendance-system\lib\site-packages\flask_restful\representations\json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\Users\achra\.conda\envs\attendance-system\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\achra\.conda\envs\attendance-system\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Users\achra\.conda\envs\attendance-system\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\achra\.conda\envs\attendance-system\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable

**Comment by sellis1234** [comment]
Have you been working on this project for a while?

**Comment by AchrafELKADIRI99** [comment]
Not really tried to work on it only for 1 day... It's an interesting project but i guess it's a complicated bug so i had no time to solve it...
Do you suggest a solution?

**Comment by sellis1234** [comment]
Only 1 day?  Why?  Jason hired you for 1 day?
Let's talk more.
Do you think you can solve the issue with more time?

Sent from Surface Duo
________________________________

**Comment by AchrafELKADIRI99** [comment]
Hired me??? What ??? I was just trying to work on a similar project that's why i found that on LinkedIn and tried to fix it! I'm not working with that Jason!

**Comment by sellis1234** [comment]
How busy are you?
