### ISSUE TITLE
Frontend not working 

### ISSUE THREAD

**Issue by barosss** [codeglitchz/attendance-system#31]
Hi,
I am facing below issue while tiring to use the frontend of the application.
I really need to make this work for a school project.
Can you please help me get the error resolved?
Thank you in advance.
(attendance-system) PS C:\Users\Cosmin\source\repos\attendance-system\backend> python.exe .\run.py
Traceback (most recent call last):
  File ".\run.py", line 1, in <module>
    from src.app import app
  File "C:\Users\Cosmin\source\repos\attendance-system\backend\src\app.py", line 10, in <module>
    from src.resources.teacher import Teacher, TeacherRegister, TeacherLogin
  File "C:\Users\Cosmin\source\repos\attendance-system\backend\src\resources\teacher.py", line 3, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (C:\Users\Cosmin\miniconda3\envs\attendance-system\lib\site-packages\werkzeug\security.py)

**Comment by H5SH** [comment]
I am probably too late, but for future visitors. They need to update or install  Werkzeug.
Below command worked for me
`pip install Werkzeug~=2.0.0 `
